Belt.scope('akasha') do |o|
  o.project('akasha', :description => 'Type checked access to browser APIs generated by by processing WebIDL', :tags => %w(travis issues))
  o.project('akasha-java', :description => 'A repository containing the source of the akasha-java artifact')
end
