Belt.scope('artemis-esf') do |o|
  o.project('artemis-framework', :description => 'A mirror of https://code.google.com/p/artemis-framework')
  o.project('artemis-gwt', :description => 'GWT port of the "Artemis Entity System Framework"')
  o.project('ashley', :description => 'A Java entity system inspired by Ash & Artemis.')
  o.project('gamadu-spaceship-warrior', :description => 'A mirror of https://code.google.com/p/spaceship-warrior')
  o.project('gamadu-starwarrior', :description => 'A mirror of https://code.google.com/p/gamadu-starwarrior')
  o.project('gamadu-tankz', :description => 'A mirror of https://code.google.com/p/gamadu-tankz')
  o.project('piemaster-artemoids', :description => 'A mirror of https://bitbucket.org/piemaster/artemoids')
  o.project('piemaster-jario', :description => 'A mirror of https://bitbucket.org/piemaster/jario')
  o.project('quake2-gwt-port')
  o.project('spaceships-demo', :description => 'SpaceBase demo application: a simulation of tens of thousands of spaceships in battle')
  o.project('GLGE', :description => 'A javascript webGL graphics library')
  o.project('open3mod', :description => 'Open 3D Model Viewer - A quick and powerful 3D model viewer')
  o.project('noa', :description => 'Experimental voxel game engine.')
  o.project('proxx', :description => 'A game of proximity')
  o.project('md2-view', :description => 'A MD2 model viewer')
end
